# Generated by Django 5.2.13 on 2026-05-10 12:23

import apps.sales.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0005_category_code'),
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(db_index=True, default=apps.sales.models._generate_rfq_number, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('READY_FOR_JOBS', 'Ready for Job Creation'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=2, help_text='1=High, 2=Normal, 3=Low')),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('scope_description', models.TextField(help_text='Service scope as requested by the customer')),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('sent_to_lab_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rfqs', to=settings.AUTH_USER_MODEL)),
                ('instruments', models.ManyToManyField(blank=True, help_text='Instruments registered against this RFQ after acceptance', related_name='rfqs', to='assets.instrument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rfqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(help_text='e.g. "Digital multimeter Fluke 87V"', max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('registered_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_line_items', to='assets.instrument')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.rfq')),
            ],
            options={
                'ordering': ['sequence', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status', 'received_date'], name='sales_rfq_status_337643_idx'),
        ),
    ]
