# Generated by Django 5.1.15 on 2026-05-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SIGN', 'Pending Signature'), ('SIGNED', 'Signed'), ('ISSUED', 'Issued'), ('SUPERSEDED', 'Superseded'), ('REVOKED', 'Revoked')], default='DRAFT', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('html_snapshot', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, help_text='SHA-256 of signed content', max_length=64)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
