# Generated by Django 5.2.13 on 2026-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='declaration_statement',
            field=models.TextField(blank=True, help_text='Formal declaration printed on every certificate above the signature block. e.g. "We hereby certify that the above instrument was calibrated using standards traceable to national/international measurement standards."'),
        ),
    ]
