# Generated by Django 5.2.13 on 2026-05-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_certificate_template_include_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='accreditation_scope',
            field=models.CharField(blank=True, help_text='Accreditation scope description, e.g. "Mass, Force, Torque — OIML R 111"', max_length=300),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='accreditation_text',
            field=models.CharField(blank=True, default='ISO/IEC 17025 Accredited', help_text='Short text in top-right, e.g. "ISO/IEC 17025 — UKAS No. 1234"', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='declaration_statement',
            field=models.TextField(blank=True, help_text='Formal declaration printed above the signature block.'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='name',
            field=models.CharField(help_text='Internal name, e.g. "Mass & Force — UKAS" or "Temperature — Default"', max_length=200),
        ),
    ]
