# Generated by Django 5.1.15 on 2026-05-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity_type', models.CharField(help_text='e.g. Length, Mass, Temperature', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DUE', 'Due for Calibration'), ('EXPIRED', 'Expired / Out of Cal'), ('RETIRED', 'Retired'), ('REPAIR', 'Under Repair')], default='ACTIVE', max_length=10)),
                ('uncertainty_value', models.DecimalField(decimal_places=10, help_text='Standard uncertainty (k=1)', max_digits=20)),
                ('calibration_date', models.DateField()),
                ('calibration_due_date', models.DateField(db_index=True)),
                ('calibration_interval_days', models.PositiveIntegerField(default=365)),
                ('traceability_chain', models.JSONField(default=list, help_text='List of dicts: [{issuing_body, cert_number, date}] up to SI')),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('issued_by', models.CharField(blank=True, help_text='External calibration lab name', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
