# Generated by Django 5.1.15 on 2026-05-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referencestandard',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodied_standards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencestandard',
            name='uncertainty_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='standards.measurementunit'),
        ),
    ]
