# Generated by Django 5.2.13 on 2026-05-03 13:50

import django.db.models.deletion
from django.db import migrations, models


def seed_from_legacy_fields(apps, schema_editor):
    """Copy existing uncertainty_value/unit into StandardUncertainty for every standard."""
    ReferenceStandard = apps.get_model('standards', 'ReferenceStandard')
    StandardUncertainty = apps.get_model('standards', 'StandardUncertainty')
    for std in ReferenceStandard.objects.all():
        if std.uncertainty_value and std.uncertainty_unit_id:
            StandardUncertainty.objects.get_or_create(
                standard=std,
                sequence=1,
                defaults={
                    'parameter': std.name,
                    'range_description': '',
                    'uncertainty_value': std.uncertainty_value,
                    'coverage_factor': 2,
                    'unit_id': std.uncertainty_unit_id,
                    'confidence_level': 95.45,
                    'notes': 'Migrated from legacy field',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardUncertainty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(help_text='e.g. Temperature, DC Voltage 1 V range', max_length=200)),
                ('range_description', models.CharField(blank=True, help_text='e.g. 0 to 100 °C', max_length=200)),
                ('uncertainty_value', models.DecimalField(decimal_places=10, help_text='Standard uncertainty u (k=1)', max_digits=20)),
                ('coverage_factor', models.DecimalField(decimal_places=2, default=2, help_text='Coverage factor k', max_digits=5)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=95.45, help_text='Confidence level %', max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uncertainties', to='standards.referencestandard')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_uncertainties', to='standards.measurementunit')),
            ],
            options={
                'ordering': ['standard', 'sequence'],
            },
        ),
        migrations.RunPython(seed_from_legacy_fields, migrations.RunPython.noop),
    ]
