# Generated by Django 5.1.15 on 2026-05-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UncertaintyContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contributor_type', models.CharField(choices=[('REF_STD', 'Reference Standard'), ('RESOLUTION', 'Instrument Resolution'), ('REPEATABILITY', 'Repeatability / Reproducibility'), ('DRIFT', 'Instrument Drift'), ('ENV', 'Environmental'), ('CUSTOM', 'Custom')], max_length=20)),
                ('distribution', models.CharField(choices=[('NORMAL', 'Normal'), ('RECTANGULAR', 'Rectangular'), ('TRIANGULAR', 'Triangular'), ('U_SHAPED', 'U-Shaped')], default='NORMAL', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('divisor', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('sensitivity_coefficient', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['method', 'sequence'],
            },
        ),
    ]
