# Generated by Django 5.2.13 on 2026-05-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Lab Manager'), ('TECHNICIAN', 'Technician'), ('REVIEWER', 'Technical Reviewer'), ('AUDITOR', 'Quality Auditor'), ('SALES', 'Sales Representative'), ('CLIENT', 'Client')], default='TECHNICIAN', max_length=20),
        ),
    ]
