# Generated by Django 5.2.13 on 2026-05-06 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(default='CalLIMS', max_length=200)),
                ('lab_subtitle', models.CharField(blank=True, default='Calibration Laboratory', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='lab_branding/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('accreditation_body', models.CharField(blank=True, max_length=200)),
                ('accreditation_number', models.CharField(blank=True, max_length=100)),
                ('footer_text', models.TextField(blank=True, help_text='Printed at the bottom of PDFs and certificates.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Settings',
                'verbose_name_plural': 'Lab Settings',
            },
        ),
        migrations.CreateModel(
            name='LicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.TextField(unique=True)),
                ('license_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('issued_to', models.CharField(max_length=200)),
                ('issued_to_email', models.EmailField(blank=True, max_length=254)),
                ('tier', models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='STARTER', max_length=20)),
                ('max_users', models.IntegerField(default=5, help_text='-1 = unlimited')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('modules_json', models.TextField(default='[]', help_text='JSON list of enabled module names.')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_licenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activated_at'],
            },
        ),
    ]
