# Generated by Django 5.1.15 on 2026-05-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.equipmentcategory'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status', 'next_calibration_date'], name='assets_equi_status_8a4d58_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['client', 'status'], name='assets_equi_client__d71675_idx'),
        ),
    ]
