# Generated by Django 5.2.13 on 2026-05-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_to_instrument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='instrument',
            new_name='assets_inst_status_acee5d_idx',
            old_name='assets_equi_status_8a4d58_idx',
        ),
        migrations.RenameIndex(
            model_name='instrument',
            new_name='assets_inst_client__d312cd_idx',
            old_name='assets_equi_client__d71675_idx',
        ),
        migrations.AddField(
            model_name='instrumentcategory',
            name='code',
            field=models.CharField(blank=True, help_text='2–5 letter uppercase prefix for auto-generated tags (e.g. ELE, TMP, MECH)', max_length=5, unique=True),
        ),
    ]
