# Generated by Django 5.1.15 on 2026-05-03 07:52

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='methods/')),
                ('coverage_factor', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=95.45, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('status', django_fsm.FSMField(choices=[('received', 'Received'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='received', max_length=50, protected=True)),
                ('priority', models.PositiveSmallIntegerField(default=2, help_text='1=High, 2=Normal, 3=Low')),
                ('received_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('humidity_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_jobs', to='assets.equipment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_jobs', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='workflows.calibrationmethod')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('nominal_value', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('measured_value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('error', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('standard_uncertainty', models.DecimalField(decimal_places=10, max_digits=20)),
                ('coverage_factor_k', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expanded_uncertainty', models.DecimalField(decimal_places=10, max_digits=20)),
                ('uncertainty_snapshot', models.JSONField(default=dict, help_text='Snapshot of calculation inputs for reproducibility')),
                ('pass_fail', models.BooleanField(blank=True, null=True)),
                ('tolerance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='workflows.calibrationjob')),
                ('reference_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_results', to='standards.referencestandard')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='standards.measurementunit')),
            ],
            options={
                'ordering': ['job', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='calibrationjob',
            index=models.Index(fields=['status', 'due_date'], name='workflows_c_status_967608_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationjob',
            index=models.Index(fields=['assigned_to', 'status'], name='workflows_c_assigne_b2b2ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='measurementresult',
            unique_together={('job', 'parameter', 'sequence')},
        ),
    ]
