# Generated by Django 5.2.13 on 2026-05-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Lower Range, Mid Point, Upper Range', max_length=100)),
                ('nominal_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tolerance_positive', models.DecimalField(blank=True, decimal_places=6, help_text='Maximum allowed positive error', max_digits=20, null=True)),
                ('tolerance_negative', models.DecimalField(blank=True, decimal_places=6, help_text='Maximum allowed negative error (store as positive number)', max_digits=20, null=True)),
                ('num_readings', models.PositiveSmallIntegerField(default=3, help_text='Repeat readings per point')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_points', to='workflows.calibrationmethod')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibration_points', to='standards.measurementunit')),
            ],
            options={
                'ordering': ['method', 'sequence'],
                'unique_together': {('method', 'sequence')},
            },
        ),
    ]
