# Generated by Django 5.2.13 on 2026-05-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_alter_certificatetemplate_accreditation_scope_and_more'),
        ('workflows', '0005_calibrationjob_rejection_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationmethod',
            name='certificate_template',
            field=models.ForeignKey(blank=True, help_text='Certificate layout used for jobs under this method. Falls back to the default template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methods', to='certificates.certificatetemplate'),
        ),
    ]
