# Generated by Django 5.2.13 on 2026-05-04 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0004_alter_certificatetemplate_declaration_statement'),
        ('workflows', '0002_calibrationpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nonconformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('CALIBRATION', 'Calibration Result'), ('CUSTOMER_COMPLAINT', 'Customer Complaint'), ('INTERNAL_AUDIT', 'Internal Audit'), ('PROFICIENCY_TEST', 'Proficiency Test'), ('EQUIPMENT_FAILURE', 'Equipment Failure'), ('OTHER', 'Other')], default='CALIBRATION', max_length=30)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], default='MINOR', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under Investigation'), ('AWAITING_VERIFICATION', 'Awaiting Verification'), ('CLOSED', 'Closed')], default='OPEN', max_length=25)),
                ('detected_date', models.DateField(default=django.utils.timezone.now)),
                ('root_cause', models.TextField(blank=True, help_text='Root cause identified during investigation')),
                ('immediate_action', models.TextField(blank=True, help_text='Action taken immediately to contain the issue')),
                ('target_closure_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformances', to='certificates.certificate')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_nonconformances', to=settings.AUTH_USER_MODEL)),
                ('detected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detected_nonconformances', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformances', to='workflows.calibrationjob')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_nonconformances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CORRECTIVE', 'Corrective Action'), ('PREVENTIVE', 'Preventive Action')], default='CORRECTIVE', max_length=15)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed — Pending Verification'), ('VERIFIED', 'Verified Effective')], default='OPEN', max_length=15)),
                ('completion_notes', models.TextField(blank=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_capas', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_capas', to=settings.AUTH_USER_MODEL)),
                ('nonconformance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='nonconformance.nonconformance')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
