# Generated by Django 5.2.13 on 2026-05-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonconformance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformance',
            name='customer_resolution',
            field=models.CharField(blank=True, choices=[('RETURN_RECALIBRATE', 'Return for Recalibration'), ('USE_AS_IS', 'Accept / Use As-Is'), ('CORRECT_REISSUE', 'Correct Certificate & Reissue')], help_text='Resolution action taken — only applicable to Customer Complaint NCs', max_length=20),
        ),
    ]
