# Generated by Django 5.2.13 on 2026-05-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('nonconformance', '0002_customer_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformance',
            name='complaint_channel',
            field=models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], help_text='How the complaint was received', max_length=10),
        ),
        migrations.AddField(
            model_name='nonconformance',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer who raised the complaint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformances', to='clients.client'),
        ),
    ]
