# Generated by Django 5.2.13 on 2026-05-03 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('accreditation_body', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PTScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
                ('measurand', models.CharField(max_length=200)),
                ('unit_symbol', models.CharField(blank=True, max_length=20)),
                ('year', models.PositiveSmallIntegerField()),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open for Registration'), ('ACTIVE', 'Sample Dispatched'), ('RESULTS_DUE', 'Results Due'), ('EVALUATING', 'Under Evaluation'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('sample_dispatch_date', models.DateField(blank=True, null=True)),
                ('results_due_date', models.DateField(blank=True, null=True)),
                ('assigned_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('assigned_std_dev', models.DecimalField(blank=True, decimal_places=6, help_text='σ_pt for z-score', max_digits=18, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='proficiency.ptprovider')),
            ],
            options={
                'ordering': ['-year', '-round_number'],
                'unique_together': {('provider', 'code', 'year', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='PTParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('SAMPLE_RECEIVED', 'Sample Received'), ('IN_PROGRESS', 'In Progress'), ('RESULTS_SUBMITTED', 'Results Submitted'), ('EVALUATED', 'Evaluated')], default='REGISTERED', max_length=20)),
                ('submitted_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('expanded_uncertainty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('coverage_factor', models.DecimalField(decimal_places=2, default=2, max_digits=5)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('z_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('en_number', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('performance', models.CharField(choices=[('SATISFACTORY', 'Satisfactory (|z|≤2)'), ('QUESTIONABLE', 'Questionable (2<|z|≤3)'), ('UNSATISFACTORY', 'Unsatisfactory (|z|>3)'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('corrective_action_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrective_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pt_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pt_participations', to='workflows.calibrationmethod')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pt_participations', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='proficiency.ptscheme')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scheme', 'technician')},
            },
        ),
    ]
