# Generated by Django 5.1.15 on 2026-05-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('CAL_DUE', 'Calibration Due'), ('CAL_OVERDUE', 'Calibration Overdue'), ('JOB_ASSIGNED', 'Job Assigned'), ('JOB_COMPLETED', 'Job Completed'), ('CERT_ISSUED', 'Certificate Issued'), ('STD_EXPIRING', 'Standard Expiring'), ('SYSTEM', 'System')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
