# Generated by Django 5.2.13 on 2026-05-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CAL_DUE', 'Calibration Due'), ('CAL_OVERDUE', 'Calibration Overdue'), ('JOB_ASSIGNED', 'Job Assigned'), ('JOB_REVIEW', 'Review Requested'), ('JOB_REJECTED', 'Job Rejected'), ('JOB_APPROVED', 'Job Approved'), ('JOB_COMPLETED', 'Job Completed'), ('CERT_ISSUED', 'Certificate Issued'), ('STD_EXPIRING', 'Standard Expiring'), ('RFQ_NEW', 'New RFQ Submitted'), ('RFQ_ACCEPTED', 'RFQ Accepted'), ('RFQ_REJECTED', 'RFQ Rejected'), ('RFQ_READY', 'RFQ Ready for Job Creation'), ('SYSTEM', 'System')], max_length=20),
        ),
    ]
